name: Release golangexamplecli binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64
        goos: [linux]
        goarch: [amd64]
    permissions:
      #contents: read # to fetch code (actions/checkout)
      #`actions: write # to attach binaries to release artifacts (skx/github-action-publish-binaries)
      contents: write #
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./
          binary_name: "golangexamplecli"
          ldflags: "-s -w"
          extra_files: LICENSE Readme.md